### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DamianLion** [YasinChan/vuepress-blog#1]
Hey I think you did a good job using the extend mechanisms of vuepress and the default theme to introduce your blog. I was looking for something like this. Did you try using the offical blog plugin to enable pagination and other features so you don't have to develop the archive by yourself

**Comment by YasinChan** [comment]
> Hey I think you did a good job using the extend mechanisms of vuepress and the default theme to introduce your blog. I was looking for something like this. Did you try using the offical blog plugin to enable pagination and other features so you don't have to develop the archive by yourself

**Comment by YasinChan** [comment]
Thanks for you suggestion! As the number of my posts increases,I will try that in the future.
